// src/components/pdf-viewer-page/pdf-menu/pdf-menu-sidebar/items/Search.vue
<script setup lang="ts">
import { RENDER_STATE, SEARCH_STATE } from '@/assets/utils/enums';
import { debounce } from '@/assets/utils/functions';
import { Loader } from '@/components/pdf-aids';
import { useDocumentStore } from '@/stores';
import type {
  getTextContentParameters,
  TextItem,
} from 'pdfjs-dist/types/src/display/api';
import { onBeforeUnmount, ref, toRaw, watch } from 'vue';

const docStore = useDocumentStore();
const selectedMatch = ref<number | null>(null);
const searchState = ref<SEARCH_STATE>(SEARCH_STATE.NULL);
const inputValue = ref<string>('');
const matches = ref<
  (
    | {
        page: number;
        text: string;
        transform: Array<number> | undefined;
        width: number;
        height: number;
      }
    | undefined
  )[]
>([]);

let searchWorker: Worker | null = null;
let pdf = toRaw(docStore.pdf);

const searchDocument = debounce(async (pattern: string) => {
  if (!pdf || !window.Worker) return;

  if (searchWorker) {
    searchWorker.terminate();
    searchWorker = null;
  }

  const textContent: { textItems: Array<TextItem>; page: number }[] = [];

  try {
    const pagesContent = await Promise.all(
      Array.from(Array(docStore.totalPages).keys()).map(async (n) => {
        const page = await pdf!.getPage(n + 1);
        const e: getTextContentParameters = {
          disableNormalization: false,
          includeMarkedContent: false,
        };
        const content = await page.getTextContent(e);
        return { textItems: content.items as TextItem[], page: n + 1 };
      })
    );

    textContent.push(...pagesContent);

    searchWorker = new Worker(new URL('./SearchWorker.ts', import.meta.url));
    selectedMatch.value = null;
    searchWorker.postMessage([pattern, textContent]);

    searchWorker.onmessage = (e) => {
      matches.value = e.data;
      if (searchWorker) searchWorker.terminate();
      searchWorker = null;
      searchState.value = SEARCH_STATE.DONE;
    };
  } catch {
    inputValue.value = '';
    searchState.value = SEARCH_STATE.NULL;
  }
});

const handleInputChange = (event: Event) => {
  const target = event.target as HTMLInputElement;
  inputValue.value = target.value;
};

const handleSelect = (index: number, page: number) => {
  const isValidIndex = index >= 0 && index < matches.value.length;
  const isValidPage = page > 0 && page <= docStore.totalPages;
  if (!isValidIndex) return;
  if (page === docStore.activePage) {
    docStore.setReRenderPage(!docStore.reRenderPage);
  } else if (isValidPage) {
    docStore.setActivePage(page);
  }
  selectedMatch.value = index;
};

onBeforeUnmount(() => {
  docStore.setReRenderPage(!docStore.reRenderPage);
});

watch(
  () => inputValue.value,
  () => {
    if (inputValue.value) {
      searchState.value = SEARCH_STATE.SEARCHING;
      searchDocument(inputValue.value);
    } else {
      searchState.value = SEARCH_STATE.NULL;
      matches.value = [];
    }
  }
);

watch(
  () => docStore.pdf,
  () => { pdf = toRaw(docStore.pdf); }
);

watch(
  () => [selectedMatch.value, docStore.renderState, docStore.activePage, matches.value],
  () => {
    const match =
      selectedMatch.value != null && matches?.value[selectedMatch.value];

    if (
      match &&
      docStore.renderState === RENDER_STATE.RENDERED &&
      match.transform &&
      docStore.activePage === match.page
    ) {
      const canvas = document.getElementById(
        'pdf-page-canvas'
      ) as HTMLCanvasElement | null;

      if (canvas) {
        const canvasHeight = parseInt(canvas.getAttribute('height')!);
        const { width, height } = match;
        const x = match.transform[4];
        const y = canvasHeight - match.transform[5] + 2 - height;
        const context = canvas.getContext('2d');

        if (context) {
          context.fillStyle = 'orange';
          context.globalAlpha = 0.5;
          context.fillRect(x, y, width, height);
        }
      }
    }
  }
);
</script>

<template>
  <div class="flex flex-col h-full gap-4">
    <!-- Search input -->
    <div class="relative">
      <svg
        class="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-gray-400 pointer-events-none"
        viewBox="0 0 16 16"
        fill="none"
      >
        <path d="M6.66667 13.3333C8.14581 13.333 9.58234 12.8379 10.7475 11.9267L14.4108 15.59L15.5892 14.4117L11.9258 10.7483C12.8375 9.58305 13.333 8.1462 13.3333 6.66667C13.3333 2.99083 10.3425 0 6.66667 0C2.99083 0 0 2.99083 0 6.66667C0 10.3425 2.99083 13.3333 6.66667 13.3333ZM6.66667 1.66667C9.42417 1.66667 11.6667 3.90917 11.6667 6.66667C11.6667 9.42417 9.42417 11.6667 6.66667 11.6667C3.90917 11.6667 1.66667 9.42417 1.66667 6.66667C1.66667 3.90917 3.90917 1.66667 6.66667 1.66667Z" fill="currentColor"/>
      </svg>
      <input
        name="search-pattern"
        class="w-full pl-9 pr-3 py-2.5 rounded-xl border border-gray-200 dark:border-white/10 bg-gray-50 dark:bg-white/5 text-gray-800 dark:text-gray-200 placeholder:text-gray-400 text-sm outline-none focus:border-secondary focus:ring-1 focus:ring-secondary/30 transition-all"
        type="text"
        :value="inputValue"
        :placeholder="$t('input-search-pattern')"
        @keydown.stop
        @input="handleInputChange"
      />
    </div>

    <!-- Initial state -->
    <div v-if="searchState === SEARCH_STATE.NULL" class="flex flex-col items-center gap-2 py-8 text-gray-400 dark:text-gray-500">
      <svg class="size-10 opacity-40" viewBox="0 0 24 24" fill="none">
        <path d="M21 21L16.5 16.5M19 11C19 15.4183 15.4183 19 11 19C6.58172 19 3 15.4183 3 11C3 6.58172 6.58172 3 11 3C15.4183 3 19 6.58172 19 11Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
      </svg>
      <span class="text-sm">{{ $t('input-search-pattern') }}</span>
    </div>

    <!-- Searching -->
    <div v-else-if="searchState === SEARCH_STATE.SEARCHING" class="flex justify-center py-8">
      <Loader :size="36" color="#36BA98" />
    </div>

    <!-- Results -->
    <div v-else-if="matches.length > 0" class="flex flex-col gap-1 overflow-auto">
      <p class="text-xs text-gray-400 dark:text-gray-500 mb-2">
        {{ $t('results') }}: <span class="font-semibold text-secondary">{{ matches.length }}</span>
      </p>
      <button
        v-for="(match, index) in matches"
        class="flex items-start justify-between gap-2 p-3 rounded-xl border border-gray-100 dark:border-white/10 hover:border-secondary/40 hover:bg-secondary/5 dark:hover:bg-secondary/10 text-left transition-all group"
        :key="index"
        :class="selectedMatch === index ? 'border-secondary/50 bg-secondary/5 dark:bg-secondary/10' : ''"
        @click="handleSelect(index, match!.page)"
      >
        <span class="text-sm text-gray-700 dark:text-gray-300 group-hover:text-gray-900 dark:group-hover:text-white line-clamp-2 flex-1 leading-snug">
          {{ match?.text }}
        </span>
        <span class="text-xs font-bold text-secondary shrink-0 mt-0.5">p.{{ match?.page }}</span>
      </button>
    </div>

    <!-- No results -->
    <div v-else class="flex flex-col items-center gap-2 py-8 text-gray-400 dark:text-gray-500">
      <span class="text-sm">{{ $t('not-found') }}</span>
    </div>
  </div>
</template>

// src/lib/components/side-menu/items/search/Search.tsx
import { useCallback, useEffect, useRef, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useDocumentContext } from '../../../hooks/useDocumentContext'
import {
  TextItem,
  getTextContentParameters,
} from 'pdfjs-dist/types/src/display/api'

// utils
import { debounce } from '../../../../../utils'
import { SEARCH_STATES } from '../../../../../utils/enums'
import { RENDERING_STATES } from '../../../../../utils/enums'

// icons
import { BiSad, BiSmile } from 'react-icons/bi'
import Loader from '../../../common/Loader'

/**
 *
 * @returns The search sidebar component
 */
const Search = () => {
  const { t } = useTranslation()

  const [searchPattern, setSearchPattern] = useState<string>('')
  const [matches, setMatches] = useState<
    (
      | {
          page: number
          text: string
          transform: Array<number> | undefined
          width: number
          height: number
        }
      | undefined
    )[]
  >([])
  const [searching, setSearching] = useState<SEARCH_STATES>(SEARCH_STATES.DONE)
  const [selectedMatch, setSelectedMatch] = useState<number | null>(null)
  let searchWorker: Worker | undefined = undefined

  const ref = useRef<HTMLInputElement | null>(null)

  const {
    pdf,
    searchPage,
    desiredScale,
    paginatorPageRender,
    setPaginatorPageRender,
    activePage,
  } = useDocumentContext()

  /**
   *
   * @param e - the change event
   * @returns - the search pattern
   *
   */
  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    return setSearchPattern(e.target.value)
  }

  /**
   * Looks for the search pattern in the whole document
   * and returns them and their page number in sidebar component
   *
   * @param pattern - the search pattern
   * @returns - the matches with their page number
   *
   */
  const searchInDocument = useCallback(
    debounce(async (pattern: string) => {
      if (window.Worker) {
        if (searchWorker) searchWorker.terminate()
        new Promise((resolve) => {
          let textContent: { textItems: Array<TextItem>; page: number }[] = []
          /**
           * Get the text content of page
           *
           * @param n - the page number
           *
           * @returns - an array of promises
           */
          const pagesContent = Array.from(Array(pdf?.numPages).keys()).map(
            (n) => {
              return pdf
                ?.getPage(n + 1)
                .then((page) => {
                  // ensure text content includes only textItems
                  let e: getTextContentParameters = {
                    disableCombineTextItems: false,
                    includeMarkedContent: false,
                  }
                  return page.getTextContent(e)
                })
                .then((content: any) => {
                  textContent = [
                    ...textContent,
                    { textItems: content.items, page: n + 1 },
                  ]
                })
            }
          )

          Promise.allSettled(pagesContent).then(() => {
            searchWorker = new Worker(
              new URL('./SearchWorker.ts', import.meta.url)
            )
            setSelectedMatch(null)
            searchWorker!.postMessage([pattern, textContent])
            searchWorker!.onmessage = (e) => {
              setMatches(e.data)
              if (searchWorker) searchWorker.terminate()
              searchWorker = undefined
              setSearching(SEARCH_STATES.DONE)
            }
          })
        })
      }
    }),
    []
  )

  /**
   * navigate to selected match
   * @param page page number of selected match
   * @param index index of match in matches array
   */
  const findMatchedText = (page: number, index: number) => {
    setPaginatorPageRender(RENDERING_STATES.RENDERING)
    searchPage(page)
    setSelectedMatch(index)
  }

  /**
   * seach with every change of searchPattern, for loaded PDFs only
   */
  useEffect(() => {
    if (searchPattern === '') return setMatches([])
    setSearching(SEARCH_STATES.LOADING)
    searchInDocument(searchPattern)
  }, [searchPattern])

  /**
   * match highlighting
   */
  useEffect(() => {
    if (
      selectedMatch != null &&
      paginatorPageRender === RENDERING_STATES.RENDERED &&
      matches &&
      matches.length > selectedMatch &&
      matches[selectedMatch]?.transform &&
      activePage === matches[selectedMatch]?.page
    ) {
      const canvas = document.getElementById(
        'evilFlowersCanvas'
      ) as HTMLCanvasElement | null

      if (canvas) {
        const x: number = matches[selectedMatch]!.transform![4]
        const y: number = matches[selectedMatch]!.transform![5] - 2
        const width: number = matches[selectedMatch]!.width
        const height: number = matches[selectedMatch]!.height
        const canvas_height = canvas.getAttribute('height')
        const context: CanvasRenderingContext2D | null = canvas.getContext('2d')
        if (context) {
          context.fillStyle = 'orange'
          context.globalAlpha = 0.4
          context.fillRect(
            x * desiredScale,
            parseInt(canvas_height!) - y * desiredScale - height * desiredScale,
            width * desiredScale,
            height * desiredScale
          )
        }
      }
    }
  }, [selectedMatch, paginatorPageRender])

  useEffect(() => {
    if (ref) ref.current?.focus()
  }, [ref])

  return (
    <>
      <div className={'flex w-full items-center justify-center'}>
        {/* Search input */}
        <input
          ref={ref}
          type={'text'}
          value={searchPattern}
          onChange={handleSearchChange}
          name="search-input"
          className="w-full p-2 text-sm border-none rounded-md bg-gray-light dark:bg-gray-dark-medium outline-none text-black dark:text-white"
          placeholder={t('search')}
          onKeyDown={(e) => {
            e.stopPropagation()
          }}
        />
      </div>
      {/* If loading */}
      {searching === SEARCH_STATES.LOADING && (
        <div className="w-full flex justify-center mt-5">
          <Loader size={30} />
        </div>
      )}
      {/* If searchPattern is empty and searching is done */}
      {searchPattern.length === 0 && searching === SEARCH_STATES.DONE && (
        <span
          className={
            'mt-5 w-full text-center text-sm whitespace-pre-wrap flex flex-col justify-center items-center'
          }
        >
          {t('searchPattern')}
          <BiSmile className="mt-2" size={30} />
        </span>
      )}
      {/* if search is done and there are no matches and ther is pattern */}
      {searching === SEARCH_STATES.DONE &&
        matches.length === 0 &&
        searchPattern.length > 0 && (
          <span
            className={
              'mt-5 w-full text-center text-sm whitespace-pre-wrap flex flex-col justify-center items-center'
            }
          >
            {t('noMatchesFound')}
            <BiSad className="mt-2" size={30} />
          </span>
        )}
      {/* if search is done and there are matches */}
      {searching === SEARCH_STATES.DONE &&
        matches.length > 0 &&
        searchPattern.length > 0 && (
          <div className="w-full flex flex-col mt-5">
            <span className={'text-sm font-medium mb-2'}>
              {t('foundResults', { count: matches.length })}
            </span>
            <div className="flex flex-col gap-2.5 w-full">
              {/* matches */}
              {matches.map((match, i) => {
                if (!match) return <></>
                return (
                  <div
                    key={i}
                    className={
                      'rounded-md bg-gray-light dark:bg-gray-dark-medium hover:bg-opacity-50 dark:hover:bg-opacity-50 cursor-pointer flex flex-col p-2 gap-2'
                    }
                    onClick={() => {
                      findMatchedText(match.page, i)
                    }}
                  >
                    <span className={'text-sm text-left'}>{match.text}</span>
                    <span className={'text-right block text-sm font-bold'}>
                      {t('pageNumber', { number: match.page })}
                    </span>
                  </div>
                )
              })}
            </div>
          </div>
        )}
    </>
  )
}
export default Search
