// src/lib/components/sidebar/Search.tsx
import { useCallback, useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useDocumentContext } from '../document/DocumentContext'
import {
  TextItem,
  getTextContentParameters,
} from 'pdfjs-dist/types/src/display/api'

// utils
import { debounce } from '../../../utils'
import { SEARCH_STATES } from '../../../utils/enums'
import { RENDERING_STATES } from '../../../utils/enums'

// icons
import { ReactComponent as SadIcon } from '../../../assets/icons/sad.svg'

/**
 *
 * @param param0 - props
 * @param param0.setActiveSidebar - function to set the active sidebar
 * @returns The search sidebar component
 */
const Search = () => {
  const { t } = useTranslation()

  const [searchPattern, setSearchPattern] = useState<string>('')
  const [matches, setMatches] = useState<
    (
      | {
          page: number
          text: string
          transform: Array<number> | undefined
          width: number
          height: number
        }
      | undefined
    )[]
  >([])
  const [searching, setSearching] = useState<SEARCH_STATES>(SEARCH_STATES.DONE)
  const [selectedMatch, setSelectedMatch] = useState<number | null>(null)
  let searchWorker: Worker | undefined = undefined
  const tmpSecuredView = false

  const { pdf, searchPage, scale, isRendering, setRendering } =
    useDocumentContext()

  /**
   *
   * @param e - the change event
   * @returns - the search pattern
   * 
   */
  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    return setSearchPattern(e.target.value)
  }

  /**
   * Looks for the search pattern in the whole document
   * and returns them and their page number in sidebar component
   *
   * @param pattern - the search pattern
   * @returns - the matches with their page number
   * 
   */
  const searchInDocument = useCallback(
    debounce(async (pattern: string) => {
      if (window.Worker) {
        if (searchWorker) searchWorker.terminate()
        new Promise((resolve) => {
          let textContent: { textItems: Array<TextItem>; page: number }[] = []
          /**
           * Get the text content of page
           *
           * @param n - the page number
           *
           * @returns - an array of promises
           */
          const pagesContent = Array.from(Array(pdf?.numPages).keys()).map(
            (n) => {
              return pdf
                ?.getPage(n + 1)
                .then((page) => {
                  // ensure text content includes only textItems
                  let e: getTextContentParameters = {
                    disableCombineTextItems: false,
                    includeMarkedContent: false,
                  }
                  return page.getTextContent(e)
                })
                .then((content: any) => {
                  textContent = [
                    ...textContent,
                    { textItems: content.items, page: n + 1 },
                  ]
                })
            }
          )

          Promise.allSettled(pagesContent).then(() => {
            searchWorker = new Worker(new URL('SearchWorker.ts', import.meta.url))
            setSelectedMatch(null)
            searchWorker!.postMessage([pattern, textContent])
            searchWorker!.onmessage = (e) => {
              setMatches(e.data)
              searchWorker!.terminate()
              searchWorker = undefined
              setSearching(SEARCH_STATES.DONE)
            }
          })
        })
      }
    }),
    []
  )
  
  /**
   * query server for search results in case of secured document.
   */
  const searchQuery = () => {
    if (searchPattern === '') {
      return setMatches([])
    }
    setSearching(SEARCH_STATES.LOADING)
    // query server with searchPattern
    // parse results into setMatches() - create new array with each elemet's attributes:
    // page - page number,
    // text - matched text preview
    // for disabled highlighting:
    // transform - undefined, 
    // width,height - 0

    // temp example for disabled highlighting - no transform matrix
    setMatches([{page: 5, text: 'ukazka: '+searchPattern, transform: undefined, width: 0, height: 0}])
    setSearching(SEARCH_STATES.DONE)
  }

  /**
   * navigate to selected match
   * @param page page number of selected match
   * @param index index of match in matches array
   */
  const findMatchedText = (page: number, index: number) => {
    setRendering(RENDERING_STATES.RENDERING)
    searchPage(page)
    setSelectedMatch(index)
  }

  /**
   * seach with every change of searchPattern, for loaded PDFs only
   */
  useEffect(() => {
    //TODO: update condition
    if (!tmpSecuredView) {     
      if (searchPattern === '') return setMatches([])
      setSearching(SEARCH_STATES.LOADING)
      searchInDocument(searchPattern)
    }
  }, [searchPattern])

  /**
   * match highlighting
   */
  useEffect(() => {
    if (
      selectedMatch != null &&
      isRendering === RENDERING_STATES.RENDERED &&
      matches &&
      matches.length > selectedMatch &&
      matches[selectedMatch]?.transform
    ) {
      const canvas = document.getElementById(
        'evilFlowersCanvas'
      ) as HTMLCanvasElement | null

      if (canvas) {
        const x: number = matches[selectedMatch]!.transform![4]
        const y: number = matches[selectedMatch]!.transform![5]
        const width: number = matches[selectedMatch]!.width
        const height: number = matches[selectedMatch]!.height
        const canvas_height = canvas.getAttribute('height')
        const context: CanvasRenderingContext2D | null = canvas.getContext('2d')
        if (context) {
          context.fillStyle = 'yellow'
          context.globalAlpha = 0.3
          context.fillRect(
            x * scale,
            parseInt(canvas_height!) - y * scale - height * scale,
            width * scale,
            height * scale
          )
        }
      }
    }
  }, [selectedMatch, isRendering])

  return (
    <>
      <div className={'flex items-center justify-center gap-0 border-none'}>
        <input
          type={'text'}
          value={searchPattern}
          onChange={handleSearchChange}
          className={`ml-4 mr-4 py-2 rounded-md bg-gray-100 dark:bg-gray-900 border border-solid dark:border-gray-500 dark:text-gray-300 outline-none focus:outline-none focus:border-gray-500 dark:focus:border-gray-300 duration-300 
            ${tmpSecuredView ? 'w-32' : ''}`
          }
          placeholder={t('searchPattern')}
        ></input>
        {tmpSecuredView && <button 
          className={'bg-transparent border-none hover:bg-gray-50 dark:hover:bg-gray-900 rounded cursor-pointer duration-200 h-6 w-4'}
          onClick={(e) => searchQuery()}>
          S
        </button>
        }
        placeholder={t('searchPattern')}
        onKeyDown={(e) => {e.stopPropagation()}}
      ></input>
      {searching === SEARCH_STATES.LOADING && (
        <div className={'w-full flex justify-center py-4'}>
          <span className={'evilflowersviewer-loader-small'}></span>
        </div>
      )}
      {searching === SEARCH_STATES.DONE && matches.length === 0 && (
        <span
          className={
            'flex justify-center items-center gap-2 text-gray-500 dark:text-gray-300 text-xs mt-4'
          }
        >
          <SadIcon width={20} />
          {t('noMatchesFound')}
        </span>
      )}
      {searching === SEARCH_STATES.DONE && matches.length > 0 && (
        <>
          <span
            className={'text-xs mx-4 mt-4 text-gray-500 dark:text-gray-300'}
          >
            {t('foundResults', { count: matches.length })}
          </span>
          {matches.map((match, i) => {
            if (!match) return <></>
            return (
              <div
                key={i}
                className={
                  'mx-4 bg-gray-100 dark:bg-gray-300 rounded-md my-1 cursor-pointer hover:bg-gray-200 px-4 py-2 duration-200'
                }
                onClick={() => {
                  findMatchedText(match.page, i)
                }}
              >
                <span className={'break-all text-xs'}>{match.text}</span>
                <span className={'text-right block break-all text-sm'}>
                  {t('pageNumber', { number: match.page })}
                </span>
              </div>
            )
          })}
        </>
      )}
    </>
  )
}
export default Search

// src/components/pdf-viewer-page/pdf-menu/pdf-menu-sidebar/items/Search.vue
<script setup lang="ts">
import { RENDER_STATE, SEARCH_STATE } from '@/assets/utils/enums';
import { debounce } from '@/assets/utils/functions';
import { Loader } from '@/components/pdf-aids';
import { useDocumentStore } from '@/stores';
import type {
  getTextContentParameters,
  TextItem,
} from 'pdfjs-dist/types/src/display/api';
import { onBeforeUnmount, ref, toRaw, watch } from 'vue';

const docStore = useDocumentStore();
const selectedMatch = ref<number | null>(null);
const searchState = ref<SEARCH_STATE>(SEARCH_STATE.NULL);
const inputValue = ref<string>('');
const matches = ref<
  (
    | {
        page: number;
        text: string;
        transform: Array<number> | undefined;
        width: number;
        height: number;
      }
    | undefined
  )[]
>([]);

let searchWorker: Worker | null = null;
let pdf = toRaw(docStore.pdf);

const searchDocument = debounce(async (pattern: string) => {
  if (!pdf || !window.Worker) return; // Early returns for checks

  // Terminate the previous worker if it's still active
  if (searchWorker) {
    searchWorker.terminate();
    searchWorker = null;
  }

  const textContent: { textItems: Array<TextItem>; page: number }[] = [];

  try {
    // Create an array of promises for getting the text content from each page
    const pagesContent = await Promise.all(
      Array.from(Array(docStore.totalPages).keys()).map(async (n) => {
        const page = await pdf!.getPage(n + 1); // Get the page (1-indexed)
        const e: getTextContentParameters = {
          disableNormalization: false,
          includeMarkedContent: false,
        };
        const content = await page.getTextContent(e);
        return { textItems: content.items as TextItem[], page: n + 1 };
      })
    );

    textContent.push(...pagesContent); // Add the page content

    // Initialize the search worker and send the pattern and content
    searchWorker = new Worker(new URL('./SearchWorker.ts', import.meta.url));
    selectedMatch.value = null;
    searchWorker.postMessage([pattern, textContent]);

    // Handle search results
    searchWorker.onmessage = (e) => {
      matches.value = e.data;
      if (searchWorker) searchWorker.terminate();
      searchWorker = null;
      searchState.value = SEARCH_STATE.DONE;
    };
  } catch {
    // When error, reset
    inputValue.value = '';
    searchState.value = SEARCH_STATE.NULL;
  }
});

const handleInputChange = (event: Event) => {
  const target = event.target as HTMLInputElement;
  inputValue.value = target.value;
};

const handleSelect = (index: number, page: number) => {
  const isValidIndex = index >= 0 && index < matches.value.length;
  const isValidPage = page > 0 && page <= docStore.totalPages;
  // Return if invalid index
  if (!isValidIndex) return;
  if (page === docStore.activePage) {
    // Trigger rerender if we're on the same page
    docStore.setReRenderPage(!docStore.reRenderPage);
  } else if (isValidPage) {
    // Set the new active page if it's valid
    docStore.setActivePage(page);
  }

  // Update the selected match
  selectedMatch.value = index;
};

// Before unmount rerender page to remove highlight
onBeforeUnmount(() => {
  docStore.setReRenderPage(!docStore.reRenderPage);
});

// Watch input and based on it determin what to do
watch(
  () => inputValue.value,
  () => {
    // If something was written set state to search and search pattern
    if (inputValue.value) {
      searchState.value = SEARCH_STATE.SEARCHING;
      searchDocument(inputValue.value);
    }
    // Else set to null and set to empty arr
    else {
      searchState.value = SEARCH_STATE.NULL;
      matches.value = [];
    }
  }
);

// Watch pdf, if change save
watch(
  () => docStore.pdf,
  () => {
    pdf = toRaw(docStore.pdf);
  }
);

// Watch selected match and renderState, if changed highlight it in document
watch(
  () => [
    selectedMatch.value,
    docStore.renderState,
    docStore.activePage,
    matches.value,
  ],
  () => {
    const match =
      selectedMatch.value != null && matches?.value[selectedMatch.value];

    if (
      match &&
      docStore.renderState === RENDER_STATE.RENDERED &&
      match.transform &&
      docStore.activePage === match.page
    ) {
      const canvas = document.getElementById(
        'pdf-page-canvas'
      ) as HTMLCanvasElement | null;

      if (canvas) {
        const canvasHeight = parseInt(canvas.getAttribute('height')!);
        const { width, height } = match;
        const x = match.transform[4];
        const y = canvasHeight - match.transform[5] + 2 - height;
        const context = canvas.getContext('2d');

        if (context) {
          context.fillStyle = 'orange';
          context.globalAlpha = 0.5;
          context.fillRect(x, y, width, height);
        }
      }
    }
  }
);
</script>

<template>
  <div class="flex flex-col h-full">
    <!-- Input -->
    <input
      name="search-pattern"
      class="input"
      type="text"
      :value="inputValue"
      placeholder="Search"
      @keydown.stop
      @input="handleInputChange"
    />

    <!-- Nothing is searched -->
    <span
      v-if="searchState === SEARCH_STATE.NULL"
      class="text-sm text-center font-bold mt-5"
    >
      {{ $t('input-search-pattern') }}
    </span>

    <!-- Searching -->
    <Loader
      v-else-if="searchState === SEARCH_STATE.SEARCHING"
      class="m-auto"
      :size="50"
      color="white"
    />

    <!-- Results -->
    <div
      v-else-if="matches.length > 0"
      class="w-full h-full mt-5 overflow-auto"
    >
      <!-- Title results -->
      <span class="text-sm font-bold"
        >{{ $t('results') }}: {{ matches.length }}</span
      >

      <!-- Button results -->
      <div class="flex flex-col w-full gap-2">
        <button
          v-for="(match, index) in matches"
          class="flex flex-col gap-2 bg-secondary hover:bg-white rounded-md p-2 text-white hover:text-black"
          :key="index"
          @click="handleSelect(index, match!.page)"
        >
          <span class="text-sm font-thin text-left">{{ match?.text }}</span>
          <span class="text-md font-bold text-right w-full"
            >Page {{ match?.page }}</span
          >
        </button>
      </div>
    </div>

    <!-- No results -->
    <span v-else class="text-sm text-center font-bold mt-5">
      {{ $t('not-found') }}
    </span>
  </div>
</template>
