// src/components/pdf-viewer-page/pdf-menu/pdf-menu-sidebar/items/Share.vue
<script setup lang="ts">
import { DAY, ERROR_LINK } from '@/assets/utils/constans';
import { MODAL_CONTENT } from '@/assets/utils/enums';
import { ValidationInput } from '@/components/pdf-aids';
import { useDocumentStore, useViewerStore } from '@/stores';
import { FaShare } from '@kalimahapps/vue-icons';
import { ref } from 'vue';

const docStore = useDocumentStore();
const viewerStore = useViewerStore();
const expaire = ref<number>(DAY);
const useEdit = ref<boolean>(false);
const inputValue = ref<string>('');
const isInappropriate = ref<boolean>(false);
const lifespanButtons: { name: string; value: number }[] = [
  { name: 'lifespan-1', value: DAY },
  { name: 'lifespan-7', value: DAY * 7 },
  { name: 'lifespan-30', value: DAY * 30 },
];

const setExpaire = (value: number) => {
  expaire.value = value;
};

const handleSubmit = async () => {
  viewerStore.setShareLink(''); // Reset link

  const expaireDate = new Date(); // create new date
  expaireDate.setHours(expaireDate.getHours() + expaire.value); // set hours with setted expaire (+ 24(day) / +24*7(week) / +24*30(month))

  const expaireDateISO: string = expaireDate.toISOString(); // ISO string format
  const pages: string | null = inputValue.value ? inputValue.value : null; // if empty set to null
  inputValue.value = ''; // Reset input

  // open qr code
  docStore.setModalContent(MODAL_CONTENT.QRCode);

  let link: string = await viewerStore.shareFunction!(pages, expaireDateISO);
  link = link ? link : ERROR_LINK;

  if (link !== ERROR_LINK) {
    const url = new URL(link);
    url.searchParams.set('annotations', `${useEdit.value}`);
    viewerStore.setShareLink(url.toString());
  }
};
</script>

<template>
  <form @submit.prevent="handleSubmit" class="flex flex-col h-full gap-5">
    <ValidationInput
      @update-input="(value: string) => inputValue = value"
      @is-inappropriate="(value: boolean)=> isInappropriate = value"
      @edit-usage="(value: boolean)=> useEdit = value"
    />

    <!-- Lifespan buttons -->
    <div class="flex flex-col gap-2">
      <div class="flex flex-col justify-evenly items-start gap-2">
        <div
          class="flex flex-row-reverse items-center gap-2 pl-1"
          v-for="item of lifespanButtons"
          :key="item.name"
        >
          <label class="cursor-pointer" @click="setExpaire(item.value)">{{
            $t(item.name)
          }}</label>
          <input
            name="expaire-date"
            @click="setExpaire(item.value)"
            :checked="item.value === expaire"
            type="radio"
            class="appearance-none h-3 w-3 text-sm bg-white hover:ring hover:ring-secondary text-black rounded-md checked:bg-secondary cursor-pointer"
          />
        </div>
      </div>
    </div>

    <!-- Spacer -->
    <span class="flex flex-1"></span>

    <!-- Submit button -->
    <button
      v-if="!isInappropriate"
      type="submit"
      class="w-full bg-secondary py-2 flex items-center justify-center rounded-md"
    >
      <FaShare class="icon size-8" />
    </button>
  </form>
</template>

// src/lib/components/side-menu/items/share/Share.tsx
import { ChangeEvent, FormEvent, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { BiInfoCircle } from 'react-icons/bi'
import { RxShare2 } from 'react-icons/rx'
import useViewerContext from '../../../hooks/useViewerContext'
import Button from '../../../common/Button'

interface IShareParams {
  setLink: (link: string) => void
  setShareQRVisibility: (mode: boolean) => void
}

/**
 * Returns the share modal component
 *
 * @param params - IShareParams, link -> link for download
 *
 * @returns - The share component
 */
const Share = (params: IShareParams) => {
  const [input, setInput] = useState<string>('')
  const [expaire, setExpaire] = useState<number>(24)
  const [isInappropriate, setIsInappropriate] = useState<boolean>(false)
  const [expaireOptions, setExpaireOptions] = useState([
    {
      name: '1d',
      value: 24,
      active: true,
    },
    {
      name: '7d',
      value: 7 * 24,
      active: false,
    },
    {
      name: '30d',
      value: 30 * 24,
      active: false,
    },
  ])
  const { t } = useTranslation()
  const { shareFunction } = useViewerContext()

  /**
   * function for handling submit form
   * @param event FormEvent -> inputs
   */
  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    if (isInappropriate) {
      // if it's inappropriate (1,4, or 1,5-), return
      return
    }
    params.setLink('') // reset link
    params.setShareQRVisibility(true) // open ShareQRCode component

    if (shareFunction) {
      // function exists
      let expaireDate = new Date() // create new date
      expaireDate.setHours(expaireDate.getHours() + expaire) // set hours with setted expaire (+ 24(day) / +24*7(week) / +24*30(month))

      const expaireDateISO: string = expaireDate.toISOString() // ISO string format
      const pages: string | null = input ? input : null // if empty set to null
      setInput('') // reset input

      let givenLink: string = await shareFunction(pages, expaireDateISO)
      givenLink = givenLink ? givenLink : 'error'
      params.setLink(givenLink)
    }
  }

  /**
   * funtion for handling input
   * @param event ChangeEvent
   */
  const handleInput = (event: ChangeEvent<HTMLInputElement>) => {
    const eventInput = event.target.value
    const pattern = /^((([0-9]+),?)*|(([0-9]+)-?))*$/ // only 1,2-6,10,3....
    const pattern2 = /^.*(([0-9]+)-([0-9]+)-)+$/ // only ...1-2- // not accepting

    if (pattern.test(eventInput) && !pattern2.test(eventInput)) {
      setInput(eventInput)
      if (
        eventInput[eventInput.length - 1] === ',' ||
        eventInput[eventInput.length - 1] === '-'
      ) {
        // if string ends with , or - do not share
        setIsInappropriate(true)
      } else {
        // it's okay
        setIsInappropriate(false)
      }
    }
  }

  /**
   * Funtion for handling buttons click by expaire options
   * @param expaire choosed expaire option
   */
  const handleExpare = (expaire: {
    name: string
    value: number
    active: boolean
  }) => {
    // update expaire
    const updatedExpaireOptions = expaireOptions.map((item) => ({
      ...item,
      active: item.name === expaire.name,
    }))
    setExpaire(expaire.value)

    setExpaireOptions(updatedExpaireOptions)
  }

  return (
    <form
      className={'w-full h-full flex flex-col justify-start items-center'}
      onSubmit={handleSubmit}
    >
      <div className={'w-full flex justify-between items-center'}>
        {/* Pages input */}
        <input
          className={
            'w-4/5 p-2 text-sm border-none rounded-md bg-gray-light dark:bg-gray-dark-medium outline-none text-black dark:text-white'
          }
          placeholder={t('shareSearch')}
          name="share-input"
          value={input}
          onChange={handleInput}
          onKeyDown={(e) => {
            e.stopPropagation()
          }}
        />
        {/* Info button */}
        <Button
          toolTip={{ text: t('shareSearchInfoToolTip'), position: 'left' }}
          icon={<BiInfoCircle size={20} className="text-blue-light" />}
        />
      </div>
      <div className="w-full flex justify-start flex-col mt-2.5">
        <span className="text-sm w-full flex justify-start flex-col mt-2.5">
          {t('shareExpaire')}
        </span>
        <div className={'flex w-full justify-between items-center mt-2.5'}>
          {/* Button for exparation */}
          {expaireOptions.map((item, i) => (
            <div
              key={i}
              className={` py-1 px-2.5 flex items-center justify-center rounded-md cursor-pointer border-none outline-none hover:bg-gray-light dark:hover:bg-gray-dark-medium ${
                item.active
                  ? 'bg-gray-light dark:bg-gray-dark-medium'
                  : 'bg-transparent'
              }`}
              onClick={() => handleExpare(item)}
            >
              {item.name}
            </div>
          ))}
        </div>
      </div>
      <span className="flex-1"></span>
      {/* Hide button if there is bad input */}
      {!isInappropriate && (
        <button
          className="w-full py-2.5 flex border-none rounded-md justify-center items-center bg-blue-dark cursor-pointer hover:bg-blue-light"
          type="submit"
        >
          <RxShare2 size={20} color="white" />
        </button>
      )}
    </form>
  )
}
export default Share
