// src/components/pdf-viewer-page/pdf-menu/pdf-menu-sidebar/items/Search.vue
<script setup lang="ts">
import { RENDER_STATE, SEARCH_STATE } from '@/assets/utils/enums';
import { debounce } from '@/assets/utils/functions';
import { Loader } from '@/components/pdf-aids';
import { useDocumentStore } from '@/stores';
import type {
  getTextContentParameters,
  TextItem,
} from 'pdfjs-dist/types/src/display/api';
import { onBeforeUnmount, ref, toRaw, watch } from 'vue';

const docStore = useDocumentStore();
const selectedMatch = ref<number | null>(null);
const searchState = ref<SEARCH_STATE>(SEARCH_STATE.NULL);
const inputValue = ref<string>('');
const matches = ref<
  (
    | {
        page: number;
        text: string;
        transform: Array<number> | undefined;
        width: number;
        height: number;
      }
    | undefined
  )[]
>([]);

let searchWorker: Worker | null = null;
let pdf = toRaw(docStore.pdf);

const searchDocument = debounce(async (pattern: string) => {
  if (!pdf || !window.Worker) return; // Early returns for checks

  // Terminate the previous worker if it's still active
  if (searchWorker) {
    searchWorker.terminate();
    searchWorker = null;
  }

  const textContent: { textItems: Array<TextItem>; page: number }[] = [];

  try {
    // Create an array of promises for getting the text content from each page
    const pagesContent = await Promise.all(
      Array.from(Array(docStore.totalPages).keys()).map(async (n) => {
        const page = await pdf!.getPage(n + 1); // Get the page (1-indexed)
        const e: getTextContentParameters = {
          disableNormalization: false,
          includeMarkedContent: false,
        };
        const content = await page.getTextContent(e);
        return { textItems: content.items as TextItem[], page: n + 1 };
      })
    );

    textContent.push(...pagesContent); // Add the page content

    // Initialize the search worker and send the pattern and content
    searchWorker = new Worker(new URL('./SearchWorker.ts', import.meta.url));
    selectedMatch.value = null;
    searchWorker.postMessage([pattern, textContent]);

    // Handle search results
    searchWorker.onmessage = (e) => {
      matches.value = e.data;
      if (searchWorker) searchWorker.terminate();
      searchWorker = null;
      searchState.value = SEARCH_STATE.DONE;
    };
  } catch {
    // When error, reset
    inputValue.value = '';
    searchState.value = SEARCH_STATE.NULL;
  }
});

const handleInputChange = (event: Event) => {
  const target = event.target as HTMLInputElement;
  inputValue.value = target.value;
};

const handleSelect = (index: number, page: number) => {
  const isValidIndex = index >= 0 && index < matches.value.length;
  const isValidPage = page > 0 && page <= docStore.totalPages;
  // Return if invalid index
  if (!isValidIndex) return;
  if (page === docStore.activePage) {
    // Trigger rerender if we're on the same page
    docStore.setReRenderPage(!docStore.reRenderPage);
  } else if (isValidPage) {
    // Set the new active page if it's valid
    docStore.setActivePage(page);
  }

  // Update the selected match
  selectedMatch.value = index;
};

// Before unmount rerender page to remove highlight
onBeforeUnmount(() => {
  docStore.setReRenderPage(!docStore.reRenderPage);
});

// Watch input and based on it determin what to do
watch(
  () => inputValue.value,
  () => {
    // If something was written set state to search and search pattern
    if (inputValue.value) {
      searchState.value = SEARCH_STATE.SEARCHING;
      searchDocument(inputValue.value);
    }
    // Else set to null and set to empty arr
    else {
      searchState.value = SEARCH_STATE.NULL;
      matches.value = [];
    }
  }
);

// Watch pdf, if change save
watch(
  () => docStore.pdf,
  () => {
    pdf = toRaw(docStore.pdf);
  }
);

// Watch selected match and renderState, if changed highlight it in document
watch(
  () => [
    selectedMatch.value,
    docStore.renderState,
    docStore.activePage,
    matches.value,
  ],
  () => {
    const match =
      selectedMatch.value != null && matches?.value[selectedMatch.value];

    if (
      match &&
      docStore.renderState === RENDER_STATE.RENDERED &&
      match.transform &&
      docStore.activePage === match.page
    ) {
      const canvas = document.getElementById(
        'pdf-page-canvas'
      ) as HTMLCanvasElement | null;

      if (canvas) {
        const canvasHeight = parseInt(canvas.getAttribute('height')!);
        const { width, height } = match;
        const x = match.transform[4];
        const y = canvasHeight - match.transform[5] + 2 - height;
        const context = canvas.getContext('2d');

        if (context) {
          context.fillStyle = 'orange';
          context.globalAlpha = 0.5;
          context.fillRect(x, y, width, height);
        }
      }
    }
  }
);
</script>

<template>
  <div class="flex flex-col h-full">
    <!-- Input -->
    <input
      name="search-pattern"
      class="input"
      type="text"
      :value="inputValue"
      placeholder="Search"
      @keydown.stop
      @input="handleInputChange"
    />

    <!-- Nothing is searched -->
    <span
      v-if="searchState === SEARCH_STATE.NULL"
      class="text-sm text-center font-bold mt-5"
    >
      {{ $t('input-search-pattern') }}
    </span>

    <!-- Searching -->
    <Loader
      v-else-if="searchState === SEARCH_STATE.SEARCHING"
      class="m-auto"
      :size="50"
      color="white"
    />

    <!-- Results -->
    <div
      v-else-if="matches.length > 0"
      class="w-full h-full mt-5 overflow-auto"
    >
      <!-- Title results -->
      <span class="text-sm font-bold"
        >{{ $t('results') }}: {{ matches.length }}</span
      >

      <!-- Button results -->
      <div class="flex flex-col w-full gap-2">
        <button
          v-for="(match, index) in matches"
          class="flex flex-col gap-2 bg-secondary hover:bg-white rounded-md p-2 text-white hover:text-black"
          :key="index"
          @click="handleSelect(index, match!.page)"
        >
          <span class="text-sm font-thin text-left">{{ match?.text }}</span>
          <span class="text-md font-bold text-right w-full"
            >Page {{ match?.page }}</span
          >
        </button>
      </div>
    </div>

    <!-- No results -->
    <span v-else class="text-sm text-center font-bold mt-5">
      {{ $t('not-found') }}
    </span>
  </div>
</template>

// src/lib/components/search/Search.tsx
import { useCallback, useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useDocumentContext } from '../document/DocumentContext'
import {
  TextItem,
  getTextContentParameters,
} from 'pdfjs-dist/types/src/display/api'

// utils
import { debounce } from '../../../utils'
import { SEARCH_STATES } from '../../../utils/enums'
import { RENDERING_STATES } from '../../../utils/enums'

// icons
import { BiSad, BiSmile } from 'react-icons/bi'

/**
 *
 * @returns The search sidebar component
 */
const Search = () => {
  const { t } = useTranslation()

  const [searchPattern, setSearchPattern] = useState<string>('')
  const [matches, setMatches] = useState<
    (
      | {
          page: number
          text: string
          transform: Array<number> | undefined
          width: number
          height: number
        }
      | undefined
    )[]
  >([])
  const [searching, setSearching] = useState<SEARCH_STATES>(SEARCH_STATES.DONE)
  const [selectedMatch, setSelectedMatch] = useState<number | null>(null)
  let searchWorker: Worker | undefined = undefined
  const tmpSecuredView = false

  const {
    pdf,
    searchPage,
    desiredScale,
    paginatorPageRender,
    setPaginatorPageRender,
    pdfViewing,
  } = useDocumentContext()

  /**
   *
   * @param e - the change event
   * @returns - the search pattern
   *
   */
  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    return setSearchPattern(e.target.value)
  }

  /**
   * Looks for the search pattern in the whole document
   * and returns them and their page number in sidebar component
   *
   * @param pattern - the search pattern
   * @returns - the matches with their page number
   *
   */
  const searchInDocument = useCallback(
    debounce(async (pattern: string) => {
      if (window.Worker) {
        if (searchWorker) searchWorker.terminate()
        new Promise((resolve) => {
          let textContent: { textItems: Array<TextItem>; page: number }[] = []
          /**
           * Get the text content of page
           *
           * @param n - the page number
           *
           * @returns - an array of promises
           */
          const pagesContent = Array.from(Array(pdf?.numPages).keys()).map(
            (n) => {
              return pdf
                ?.getPage(n + 1)
                .then((page) => {
                  // ensure text content includes only textItems
                  let e: getTextContentParameters = {
                    disableCombineTextItems: false,
                    includeMarkedContent: false,
                  }
                  return page.getTextContent(e)
                })
                .then((content: any) => {
                  textContent = [
                    ...textContent,
                    { textItems: content.items, page: n + 1 },
                  ]
                })
            }
          )

          Promise.allSettled(pagesContent).then(() => {
            searchWorker = new Worker(
              new URL('SearchWorker.ts', import.meta.url)
            )
            setSelectedMatch(null)
            searchWorker!.postMessage([pattern, textContent])
            searchWorker!.onmessage = (e) => {
              setMatches(e.data)
              searchWorker!.terminate()
              searchWorker = undefined
              setSearching(SEARCH_STATES.DONE)
            }
          })
        })
      }
    }),
    []
  )

  /**
   * query server for search results in case of secured document.
   */
  const searchQuery = () => {
    if (searchPattern === '') {
      return setMatches([])
    }
    setSearching(SEARCH_STATES.LOADING)
    // query server with searchPattern
    // parse results into setMatches() - create new array with each elemet's attributes:
    // page - page number,
    // text - matched text preview
    // for disabled highlighting:
    // transform - undefined,
    // width,height - 0

    // temp example for disabled highlighting - no transform matrix
    setMatches([
      {
        page: 5,
        text: 'ukazka: ' + searchPattern,
        transform: undefined,
        width: 0,
        height: 0,
      },
    ])
    setSearching(SEARCH_STATES.DONE)
  }

  /**
   * navigate to selected match
   * @param page page number of selected match
   * @param index index of match in matches array
   */
  const findMatchedText = (page: number, index: number) => {
    setPaginatorPageRender(RENDERING_STATES.RENDERING)
    searchPage(page)
    setSelectedMatch(index)
  }

  /**
   * seach with every change of searchPattern, for loaded PDFs only
   */
  useEffect(() => {
    if (!tmpSecuredView) {
      if (searchPattern === '') return setMatches([])
      setSearching(SEARCH_STATES.LOADING)
      searchInDocument(searchPattern)
    }
  }, [searchPattern])

  /**
   * match highlighting
   */
  useEffect(() => {
    if (
      selectedMatch != null &&
      paginatorPageRender === RENDERING_STATES.RENDERED &&
      matches &&
      matches.length > selectedMatch &&
      matches[selectedMatch]?.transform
    ) {
      let canvas
      pdfViewing === 'paginator'
        ? (canvas = document.getElementById(
            'evilFlowersCanvas'
          ) as HTMLCanvasElement | null)
        : (canvas = document.getElementById(
            'evilFlowersCanvas' + matches[selectedMatch]!.page
          ) as HTMLCanvasElement | null)

      if (canvas) {
        const x: number = matches[selectedMatch]!.transform![4]
        const y: number = matches[selectedMatch]!.transform![5] - 3
        const width: number = matches[selectedMatch]!.width
        const height: number = matches[selectedMatch]!.height
        const canvas_height = canvas.getAttribute('height')
        const context: CanvasRenderingContext2D | null = canvas.getContext('2d')
        if (context) {
          context.fillStyle = 'orange'
          context.globalAlpha = 0.4
          context.fillRect(
            x * desiredScale,
            parseInt(canvas_height!) - y * desiredScale - height * desiredScale,
            width * desiredScale,
            height * desiredScale
          )
        }
      }
    }
  }, [selectedMatch, paginatorPageRender])

  return (
    <>
      <div className={'search-input-container'}>
        <input
          type={'text'}
          value={searchPattern}
          onChange={handleSearchChange}
          name="search-input"
          className={'search-input'}
          placeholder={t('search')}
          onKeyDown={(e) => {
            e.stopPropagation()
          }}
        />
        {/* {tmpSecuredView && (
          <button
            className={
              'bg-transparent border-none hover:bg-gray-400 dark:hover:bg-gray-900 rounded cursor-pointer duration-200 h-6 w-4'
            }
            onClick={(e) => searchQuery()}
          >
            S
          </button>
        )} */}
      </div>
      {searching === SEARCH_STATES.LOADING && (
        <div className={'search-loader'}>
          <span className={'viewer-loader-small'}></span>
        </div>
      )}
      {searchPattern.length === 0 && (
        <span
          className={'search-tips-titles'}
          style={{ whiteSpace: 'pre-wrap' }}
        >
          {t('searchPattern')}
          <BiSmile className="viewer-button-icon" />
        </span>
      )}
      {searching === SEARCH_STATES.DONE &&
        matches.length === 0 &&
        searchPattern.length > 0 && (
          <span className={'search-tips-titles'}>
            {t('noMatchesFound')}
            <BiSad className="viewer-button-icon" />
          </span>
        )}
      {searching === SEARCH_STATES.DONE &&
        matches.length > 0 &&
        searchPattern.length > 0 && (
          <div className="search-found-results-container">
            <span className={'search-found-results'}>
              {t('foundResults', { count: matches.length })}
            </span>
            <div className="search-matches-container">
              {matches.map((match, i) => {
                if (!match) return <></>
                return (
                  <div
                    key={i}
                    className={'search-mached-text-container'}
                    onClick={() => {
                      findMatchedText(match.page, i)
                    }}
                  >
                    <span className={'search-mached-pattern'}>
                      {match.text}
                    </span>
                    <span className={'search-mached-page'}>
                      {t('pageNumber', { number: match.page })}
                    </span>
                  </div>
                )
              })}
            </div>
          </div>
        )}
    </>
  )
}
export default Search
