// src/lib/components/common/Loader.tsx
interface ILoaderProps {
  size: number
}

const Loader = ({ size }: ILoaderProps) => {
  return (
    <div style={{ height: size + 'px', width: size + 'px' }}>
      <div className="w-full h-full border-4 border-black dark:border-white border-t-4 border-t-blue-dark dark:border-t-blue-dark rounded-full animate-spin"></div>
    </div>
  )
}

export default Loader

// src/components/pdf-aids/Loader.vue
<script setup lang="ts">
interface ILoaderProps {
  size: number;
  color: string;
}
// Props
const { size, color } = defineProps<ILoaderProps>();
</script>

<template>
  <div class="w-full h-full flex justify-center items-center">
    <div class="flex justify-center items-center z-40">
      <div
        class="w-14 h-14 border-t-4 border-solid rounded-full animate-spin"
        :style="{ width: `${size}px`, height: `${size}px`, borderColor: color }"
      ></div>
    </div>
  </div>
</template>
