// src/components/pdf-viewer-page/pdf-menu/pdf-menu-sidebar/items/Info.vue
<script setup lang="ts">
import type { IPDFMetadataProps } from '@/assets/utils/interfaces';
import { useDocumentStore } from '@/stores';
import { ref, onMounted, computed, toRaw, watch } from 'vue';

const docStore = useDocumentStore();
const metadata = ref<Partial<IPDFMetadataProps>>({});
let pdf = toRaw(docStore.pdf);

const filteredMetadata = computed(() => {
  const result: Partial<IPDFMetadataProps> = {
    Author: metadata.value.Author,
    Title: metadata.value.Title,
    Pages: metadata.value.Pages,
    CreationDate: metadata.value.CreationDate,
    ModificationDate: metadata.value.ModificationDate,
    Description: metadata.value.Description,
    Identificator: metadata.value.Identificator,
    Creator: metadata.value.Creator,
    Keywords: metadata.value.Keywords,
    Producer: metadata.value.Producer,
    Subject: metadata.value.Subject,
    Language: metadata.value.Language,
    PDFFormatVersion: metadata.value.PDFFormatVersion,
  };
  return Object.fromEntries(
    Object.entries(result).filter(([_, value]) => value)
  );
});

const formatDate = (dateString: string): string => {
  const year = Number(dateString.substring(2, 4)) + 2000;
  const month = Number(dateString.substring(6, 8)) - 1;
  const day = Number(dateString.substring(8, 10));
  const hour = Number(dateString.substring(10, 12));
  const minute = Number(dateString.substring(12, 14));
  const second = Number(dateString.substring(14, 16));
  const newDate = new Date(year, month, day, hour, minute, second);
  return newDate.toLocaleString([], {
    weekday: 'short',
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: 'numeric',
    second: 'numeric',
    timeZoneName: 'short',
  });
};

onMounted(async () => {
  if (pdf?.getMetadata) {
    const meta = (await pdf.getMetadata()) as any;
    if (meta.info?.CreationDate?.startsWith('D:')) {
      meta.info.CreationDate = formatDate(meta.info.CreationDate);
    }
    if (meta.info?.ModDate?.startsWith('D:')) {
      meta.info.ModDate = formatDate(meta.info.ModDate);
    }
    metadata.value = meta.info;
  }
});

watch(
  () => docStore.pdf,
  () => { pdf = docStore.pdf; }
);
</script>

<template>
  <div class="flex flex-col gap-[10px]">
    <div
      v-for="(value, key) in filteredMetadata"
      :key="key"
      class="flex flex-col gap-[5px] py-px"
    >
      <span class="sidebar-label">{{ $t(key.toString()) }}</span>
      <span class="sidebar-value">{{ value }}</span>
    </div>
  </div>
</template>

// src/lib/components/side-menu/items/Info.tsx
import { ReactNode, useEffect, useState } from 'react'
import { useDocumentContext } from '../../hooks/useDocumentContext'
import { useTranslation } from 'react-i18next'

interface IPdfMetadataProps {
  Author?: string
  Title?: string
  Pages?: number
  CreationDate?: string
  ModificationDate?: string
  Description?: string
  Identificator?: number
  Creator?: string
  Keywords?: string
  Producer?: string
  Subject?: string
  PDFFormatVersion?: string
}

interface IInfoRowProps {
  title: ReactNode
  value: ReactNode
}

const InfoRow = ({ title, value }: IInfoRowProps) => (
  <div className={'flex flex-col mb-2'}>
    <span className={'text-[15px] font-bold'}>{title}</span>
    <span className={'text-sm break-words'}>{value}</span>
  </div>
)

/**
 * Shows the document information based on metadata from the document
 * in a sidebar component
 * 
 * @param param0 - props
 * @param param0.setActiveSidebar - function to set sidebar state
 
 * @returns - The document information sidebar component
 */
const Info = () => {
  const { t } = useTranslation()
  const { pdf } = useDocumentContext()
  const [metadata, setMetadata] = useState<any>([])

  let result: IPdfMetadataProps = {
    Author: metadata?.Author,
    Title: metadata?.Title,
    Pages: metadata?.Pages,
    CreationDate: metadata?.CreationDate,
    ModificationDate: metadata?.ModDate,
    Description: metadata?.Description,
    Identificator: metadata?.Identificator,
    Creator: metadata?.Creator,
    Keywords: metadata?.Keywords,
    Producer: metadata?.Producer,
    Subject: metadata?.Subject,
    PDFFormatVersion: metadata?.PDFFormatVersion,
  }

  const formatDate = (dateString: string): string => {
    const year = Number(dateString.substring(2, 4))
    const month = Number(dateString.substring(6, 2)) - 1
    const day = Number(dateString.substring(8, 2))
    const hour = Number(dateString.substring(10, 2))
    const minute = Number(dateString.substring(12, 2))
    const second = Number(dateString.substring(14, 2))
    const newDate = new Date(year, month, day, hour, minute, second)
    return newDate.toLocaleString([], {
      weekday: 'short',
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: 'numeric',
      minute: 'numeric',
      second: 'numeric',
      timeZoneName: 'short',
    })
  }

  useEffect(() => {
    pdf
      ?.getMetadata()
      .then((meta: any) => {
        if (meta.info.CreationDate.substr(0, 2) == 'D:') {
          const creationDateString = meta.info.CreationDate
          const formattedCreationDate = formatDate(creationDateString)
          meta.info.CreationDate = formattedCreationDate
        }
        if (meta.info.ModDate.substr(0, 2) == 'D:') {
          const modDateString = meta.info.ModDate
          const formattedCreationDate = formatDate(modDateString)
          meta.info.ModDate = formattedCreationDate
        }
        setMetadata(meta.info)
      })
      .catch((err) => {
        console.error(err)
      })
  }, [pdf])

  return (
    <>
      {Object.keys(result)
        .filter((key) => result[key as keyof IPdfMetadataProps])
        .map((key) => (
          <InfoRow
            key={key}
            title={t(key)}
            value={result[key as keyof IPdfMetadataProps]}
          />
        ))}
    </>
  )
}
export default Info
